import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import dotenv from "dotenv"

dotenv.config()

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HeadP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased flex flex-col min-h-screen`}>
        <header className="shrink-0">
          <Navbar />
        </header>
        <main className="flex-1 overflow-auto">
          <div className="min-h-screen">{children}</div>
          <Footer/>
        </main>
      </body>
    </html>
  );
}
